### ISSUE TITLE
Extension broken with 0.4.5-pre1

### ISSUE THREAD

**Issue by mateon1** [xicombd/ipfs-chrome-station#14]
In 0.4.5, the format of the /api/v0/swarm/peers endpoint changes, so the extension shows that the daemon is offline regardless of its status.

**Comment by atommixz** [comment]
not work for me on 0.4.5

**Comment by elasticdog** [comment]
I recently wiped my laptop and now have a fresh ipfs / ipfs-station (v1.1.0) install on Chrome (v57.0.2987.110 64-bit) running on macOS Sierra and the extension is only showing OFF, although the daemon is running. Any troubleshooting steps I can take to debug why it doesn't pick up that IPFS is on the network?

**Comment by xicombd** [comment]
@elasticdog can you try adding the CORS headers? 
`ipfs config --json API.HTTPHeaders '{"Access-Control-Allow-Origin": ["*"]}'`

It might be the same problem as @AlexBeLi is describing at https://github.com/xicombd/ipfs-chrome-station/pull/15.

**Comment by elasticdog** [comment]
@xicombd that fixed it indeed!

**Comment by xicombd** [comment]
@elasticdog great! I'll add a note to the offline screen about that then :)
