### ISSUE TITLE
update webgui hash

### ISSUE THREAD

**Issue by davidak** [xicombd/ipfs-chrome-station#8]
replace `QmRyWyKWmphamkMRnJVjUTzSFSAAZowYP4rnbgnfMXC9Mr`
with `QmU3o9bvfenhTKhxUakbYrLDnZU7HezAVxPM6Ehjw9Xjqy` (from quick-start)
or directly use `http://localhost:5001/webui`

in the old one is the peers view not working (CONNECTED TO X PEER) and it is not locaziled.

**Comment by xicombd** [comment]
Thanks for noticing this! I just published a new version with the fix :octocat:
